name = "cf_ai_dungeon_master"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

# [ai]
# binding = "AI"

[[r2_buckets]]
binding = "LOG_BUCKET"
bucket_name = "dungeon-logs"

[durable_objects]
bindings = [
  { name = "GAME_SESSION", class_name = "GameSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameSession"]